#!/usr/bin/python

import sys
import dbus

bus = dbus.SessionBus()
client = dbus.Interface(bus.get_object("org.openobex.client", "/"),
							"org.openobex.Client")

if (len(sys.argv) < 4):
	print "Usage: %s <device> <clientfile> <file>" % (sys.argv[0])
	sys.exit(1)

print "Creating Session"
session_path = client.CreateSession(sys.argv[1], { "Target": "OPP" })
opp = dbus.Interface(bus.get_object("org.openobex.client",
					session_path),
					"org.openobex.ObjectPush")

opp.ExchangeBusinessCards(sys.argv[2], sys.argv[3])
