#!/usr/bin/python

import os
import sys
import dbus

bus = dbus.SessionBus()
client = dbus.Interface(bus.get_object("org.openobex.client", "/"),
						"org.openobex.Client")

if (len(sys.argv) < 3):
	print "Usage: %s <device> <file> [file*]" % (sys.argv[0])
	sys.exit(1)

files = [os.path.realpath(f) for f in sys.argv[2:]]

print "Creating Session"
session_path = client.CreateSession(sys.argv[1], { "Target": "OPP" })
opp = dbus.Interface(bus.get_object("org.openobex.client", session_path),
					"org.openobex.ObjectPush")

for f in files:
	opp.SendFile(f)
